server:
  port: 8092


#开发环境配置
spring:
  application:
    name: springboot-dubbo-commodity
  datasource:
    name: springboot-dubbo-commodity
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #mysql驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&useAffectedRows=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000

  #redis缓存
  redis:
    #redis数据库索引
    database: 0
    #redis服务器地址、这里是本地
    host: 127.0.0.1
    #redis连接密码、默认为空
    password:
    #redis端口号
    port: 6379
    #连接超时时间
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负数没有限制）
        max-active: 8
        #连接池最大阻塞等待时间
        max-wait: 60
        #连接池中最大空闲连接
        max-idle: 8
        #连接池中最小空闲连接
        min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 2000 #缓存超时时间ms
      cache-null-values: false #是否缓存空值

  #rabbitmq
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    #消息发送至 exchange 才 callback
    publisher-confirms: true
    #消息发送至 queue 失败才 callback
    publisher-returns: true
    #消费消息手动删除
    listener:
      direct:
        acknowledge-mode: manual
    template:
      mandatory: true
      #重新投递时间（分钟）
      receive-timeout: 1
    virtual-host: /


  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false




#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dingding.seckill.entity
  configuration:
    # 使用jdbc的getGeneratedKeys 可以获取数据库自增主键值
    use-generated-keys: true
    # 使用列别名替换列名，默认true。如：select name as title from table
    use-column-label: true
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true


dubbo:
  protocol:
    name: dubbo
    port: 20892
  application:
    name: seckill-commodity
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
