server:
  port: 8019
  servlet:
    context-path: /api

#开发环境配置
spring:
  profiles:
    active: dev
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #mysql驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 12345678
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000

  #redis缓存
  redis:
    #redis数据库索引
    database: 0
    #redis服务器地址、这里是本地
    host: 127.0.0.1
    #redis连接密码、默认为空
    password:
    #redis端口号
    port: 6379
    #连接超时时间
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负数没有限制）
        max-active: 8
        #连接池最大阻塞等待时间
        max-wait: 60
        #连接池中最大空闲连接
        max-idle: 8
        #连接池中最小空闲连接
        min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 2000 #缓存超时时间ms
      cache-null-values: false #是否缓存空值

  #rabbitmq
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    #消息发送至 exchange 才 callback
    publisher-confirms: true
    #消息发送至 queue 失败才 callback
    publisher-returns: true
    #消费消息手动删除
    listener:
      direct:
        acknowledge-mode: manual
    template:
      mandatory: true
      #重新投递时间（分钟）
      receive-timeout: 1
    virtual-host: /


  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8







